# Numpy
- It is also called numerical python.
- It is faster than Python lists.
- Uses less memory
- Low level, C optimized backend.
- Support vectorized operation (no need of loop)
- using SIMD (single instruction mulltiple data)
- Contigious memory allocation.

In [1]:
# We can verify it by a performance test. 

In [2]:
# add two lists (without using Numpy)
import time

l1 = list(range(1_000_000_0))
l2 = list(range(1_000_000_0))

          
start = time.time()
add = [x+y for x,y in zip (l1, l2)]
end = time.time()

print("Total time taken:",end - start, "seconds")

Total time taken: 1.9556910991668701 seconds


In [3]:
# now using Numpy arange , total time taken is almost 10 times less.
import numpy as np
import time

arr1 = np.array(l1)
arr2 = np.array(l2)

start = time.time()
add = arr1 + arr2
end = time.time()

print("Total time taken:", end-start, "seconds")

Total time taken: 0.226423978805542 seconds


In [4]:
x1 = [x for x in range(1,11) if x%2 == 0]
x2 = [y for y in range(1,11) if y%2 != 0]

list(zip(x1 , x2))

[(2, 1), (4, 3), (6, 5), (8, 7), (10, 9)]

In [5]:
# Creating 1D , 2D array using numpy
arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [6]:
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [7]:
arr1D.shape

(5,)

In [8]:
arr2D.shape     #  2 means 2 rows and 3 means 3 columns

(2, 3)

In [9]:
type(arr2)

numpy.ndarray

In [10]:
ar3 = np.array([1,2,3,4,5, "hello", 2.3, True]) # if we wrote element of different datatypes in np.array() ,
                                                # it convert all the elements datatype into one single datatype

In [11]:
ar3

array(['1', '2', '3', '4', '5', 'hello', '2.3', 'True'], dtype='<U32')

In [12]:
# check memory utilization
# Python list vs numpy array
import sys

lt = list(range(1000))
arr = np.array(lt)

print("Memory taken by python list:", sys.getsizeof(lt) * len(lt) , "bytes")
print("Memory taken by numpy array:", arr.nbytes , "bytes")


Memory taken by python list: 8056000 bytes
Memory taken by numpy array: 8000 bytes


In [13]:
l3 = [x**2 for x in range(1,6)]

l4 = [1,2,3,4,5]
ar3 = np.array(l4) **2

print(l3)  
print(ar3)

[1, 4, 9, 16, 25]
[ 1  4  9 16 25]


In [14]:
# Task1
import time
st = time.time()
l3 = [x**2 for x in lt]
en = time.time()

sr = time.time()
ar3 = arr **2
ed = time.time()

print("With loops time taken by python list:", en-st) 
print("Without loops time taken by numpy array to perform the same task:", ed-sr)
print("Numpy vectorization is", (en-st)/(ed-sr), "times faster")

With loops time taken by python list: 0.0019881725311279297
Without loops time taken by numpy array to perform the same task: 0.00030922889709472656
Numpy vectorization is 6.429452582883577 times faster
