# Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr =np.array([2,4,5,6,9])

In [3]:
arr

array([2, 4, 5, 6, 9])

In [4]:
arr1 = np.array([[4,7,0,4,15],[1,6,8,2,4]]) #2D

In [5]:
arr1

array([[ 4,  7,  0,  4, 15],
       [ 1,  6,  8,  2,  4]])

In [6]:
arr2 = np.array([[9,8,2],[1,2,7],[4,5,1]])

In [7]:
arr2

array([[9, 8, 2],
       [1, 2, 7],
       [4, 5, 1]])

In [8]:
arr2.shape

(3, 3)

In [9]:
arr2.diagonal()

array([9, 2, 1])

In [10]:
arr2.dtype

dtype('int64')

In [11]:
arr1.flatten()  # convert 2D into 1D

array([ 4,  7,  0,  4, 15,  1,  6,  8,  2,  4])

In [12]:
arr2.max()

np.int64(9)

In [13]:
arr3 = np.array([[[1,2],[4,5]],[[6,7],[8,9]]])

In [14]:
arr3.ndim # it tells the dimension of array

3

In [15]:
arr4 = np.array([[[[1,2],[4,5],[5,4]]],[[[6,7],[8,9],[9,8]]]])

In [16]:
arr4.ndim

4

In [17]:
arr3

array([[[1, 2],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [18]:
arr2.size

9

In [19]:
arr1.reshape(5,2)

array([[ 4,  7],
       [ 0,  4],
       [15,  1],
       [ 6,  8],
       [ 2,  4]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
y = np.array(range(10,101))

In [23]:
y.shape

(91,)

In [24]:
np.full((3,3), 8)   #it creates 3*3 matrix of 8 number

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [25]:
np.eye(5)       # create identity matrix which has 1 on diagonols

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.arange(1, 50, 5)  # starting val, ending val, increment

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [27]:
np.linspace(1, 2, 5) #starting val, ending val, amount of values written from started to end (evenly spaced)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
carr =np.array([[2,4,5,6], [4,9,1,2]] , dtype = str) # we can also define datatype what we wnat while creaing array

In [29]:
carr

array([['2', '4', '5', '6'],
       ['4', '9', '1', '2']], dtype='<U1')

In [30]:
carr1 = np.array([[2,5,6,8]], dtype = np.float32) 

In [31]:
carr1

array([[2., 5., 6., 8.]], dtype=float32)

In [32]:
int_arr = carr1.astype(np.int64)   # convert float to int

In [33]:
print(int_arr)

[[2 5 6 8]]
