In [1]:
# Indexing and slicing

In [2]:
import numpy as np

In [10]:
arr1 = np.array([2,4,6,8,9,3,0,78])

In [11]:
arr1[0]      #it returns the value present at that index

np.int64(2)

In [13]:
arr1[7]

np.int64(78)

In [14]:
arr1[3:6]

array([8, 9, 3])

In [15]:
arr1[5:]

array([ 3,  0, 78])

In [16]:
arr1[:8]

array([ 2,  4,  6,  8,  9,  3,  0, 78])

In [19]:
arr1[::2]

array([2, 6, 9, 0])

In [21]:
arr1[2:7:2]           # start:End:Increment

array([6, 9, 0])

In [22]:
# when we use slicing and indexing in numpy , it only show the view. It don't provide copy of original array. In this way 
# it is memory efficient.
# Let understand with the example

In [23]:
arr2 = np.array([3,6,9,12,15])

In [24]:
arr2[1:5]

array([ 6,  9, 12, 15])

In [25]:
arr2[2] = 10       # it directly updates changes in the array we created.

In [26]:
arr2

array([ 3,  6, 10, 12, 15])

In [27]:
# we can also access elements using indexing from 2D array
arr = np.array([[5,6,7],[1,2,3]])

In [28]:
arr[0]

array([5, 6, 7])

In [29]:
arr[0][0]

np.int64(5)

In [30]:
arr[1][2]

np.int64(3)

In [31]:
# Fancy indexing

In [32]:
arr4 = np.array([2,3,4,5,6,7,8])

In [43]:
arr4[[0,2,4]]    # it shows the element present at that index only

array([2, 4, 6])

In [1]:
# Boolean Masking

In [3]:
arr5 = np.array([2,5,7,9,1,6])

In [4]:
mask = arr5 > 5  # it shows all elements greater than 5

In [5]:
print(arr5[mask])

[7 9 6]
