# Excercise

In [1]:
import numpy as np

In [2]:
# Question 1

In [3]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
ar1.shape

(3, 3)

In [5]:
# Question 2

In [6]:
ar2 = np.array([1.1, 2.2, 3.3])

In [7]:
convertintoInt = ar2.astype(np.int32)

In [8]:
convertintoInt

array([1, 2, 3], dtype=int32)

In [9]:
# Question 3 (Fancy Indexing)

In [10]:
ar3 = np.array([1,2,3,4,5,6])

In [11]:
indx = [1,3,5] 

In [12]:
print(ar3[indx]) # print even numbers

[2 4 6]


In [13]:
# Question 4

In [14]:
ar4 = np.array([1,2,3,4,5,6,7,8,9])

In [15]:
ar4.shape

(9,)

In [16]:
ar4.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# Question 5 (Boolean Masking)

In [18]:
ar5 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [19]:
mask = ar5 > 50

In [20]:
ar5[mask]  #print values that are greater than 50

array([ 60,  70,  80,  90, 100])