# MultiDimensional Indexing and Axis

- Numpy allows us to work with multidimensional arrays where indexing and axis manipulation play a crucial role.
- Understanding how indexing work across multiple dimensions is essential for data science and ML tasks.
- In case of 2D array If we write axis = 0 it means this operation is performed rowwise and If we write axis = 1 it means this operation is performed columnwise.

- 1D array (Axis 0)
- 2D array (Axis 0 = rows, Axis 1 = column)
- 3D array (Axis 0 = depth, Axis 1 = rows, Axis 2 = column 

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],
                 [6,7,8],
                 [3,5,1]])

In [3]:
rowwiseproduct = np.prod(arr1, axis=0)

In [4]:
rowwiseproduct

array([18, 70, 24])

In [5]:
columnwiseproduct = np.prod(arr1, axis=1)

In [6]:
columnwiseproduct

array([  6, 336,  15])

In [7]:
print(arr1)

[[1 2 3]
 [6 7 8]
 [3 5 1]]


In [8]:
# check the dimension of array
arr1.ndim

2

### Multidimensional indexing using Numpy

In [9]:
# 2D array
arr2D = np.array([
        [4,9,1],
        [8,1,2],
        [4,7,5]
        ])

In [10]:
arr2D.shape

(3, 3)

In [11]:
arr2D.ndim

2

In [12]:
# Multidimensional indexing
print(arr2D[2, 1])

7


In [13]:
# Slicing in 2D
print(arr2D[1:3, 0:2])

[[8 1]
 [4 7]]


In [14]:
print(arr2D[:, 0:1])

[[4]
 [8]
 [4]]


In [15]:
arr3D = np.array([
        [[1,2,4],  #row 0 ----\
         [5,6,7],  #row 1 ----- > Depth 0  
         [4,5,6]], #row 2 ----/
    
        [[3,7,8],  #row 0 ----\
         [3,4,5],  #row 1 ----- > Depth 1
         [8,9,0]], #row 2 ----/
    
        [[0,1,4], #row 0 ----\
         [2,5,7], #row 1 ----- > Depth 2
         [3,2,1]] #row 2 ----/
        ])

In [16]:
arr3D.shape

(3, 3, 3)

In [17]:
arr3D.ndim

3

In [18]:
# Multidimensional indexing
print(arr3D[1, 0, 2])   # 1 mean depth, 0 mean first row of this depth, 2 mean 3rd element of depth 1 of first row 

8


In [19]:
# we can also do multidimensional slicing using numpy
print(arr3D[0:3 , 1:3, 1:3])  # depth from 0th index to 2(3-1), row from index 1 to 2 , column from index 1 to 2 of given rows

[[[6 7]
  [5 6]]

 [[4 5]
  [9 0]]

 [[5 7]
  [2 1]]]


In [20]:
print(arr3D[: , 0, 1:2])

[[2]
 [7]
 [1]]


In [21]:
#practice
arr3D1 = np.array([
        [[1,2,3],
         [4,5,6]],
    
        [[7,8,9],
         [10,11,12]],
    
        [[13,14,15],
         [16,17,18]]
        ])

In [22]:
# get the first row from each sheet
print(arr3D1[: , 0, :])

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


In [23]:
# get the first column of each row of the 1st sheet
print(arr3D1[0, :, 0])

[1 4]


In [24]:
# replace all elements in column 2 with 0 of 2nd sheet
arr3D1[1, :, 2] = 0  #it will replace 9 and 12 with 0

In [25]:
print(arr3D1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  0]
  [10 11  0]]

 [[13 14 15]
  [16 17 18]]]


In [26]:
# replace all elements in row 1 with 0 of the 3rd sheet
arr3D1[2, 0, :] = 0

In [27]:
print(arr3D1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  0]
  [10 11  0]]

 [[ 0  0  0]
  [16 17 18]]]
