- Numpy arrays are *homogeneous*. It means it can only store elements of the same type. This isdifferent from python lists which store elements of mixed data tyoes.
- Numpy supports various datatypes and understanding them is crucial for optimizing memory usage and performance.    

In [1]:
import numpy as np

In [2]:
arr1 = np.array([2,5,8,7])

In [3]:
arr1.dtype

dtype('int64')

In [4]:
arr2 = np.array([5.2, 8.9, 2.7, 9.6])

In [5]:
arr2.dtype

dtype('float64')

In [6]:
arr3 = np.array([True, False, True])

In [7]:
arr3.dtype

dtype('bool')

In [8]:
arr4 = np.array(['aeu', 'v', 'd', 'h'])

In [9]:
arr4.dtype

dtype('<U3')

In [10]:
# complex datatypes
arr5 = np.array([2+4j, 3+6j, 1+7j], dtype = 'complex64')

In [11]:
arr5

array([2.+4.j, 3.+6.j, 1.+7.j], dtype=complex64)

In [12]:
arr5.nbytes

24

In [13]:
arr6 = np.array(['apple', 'mango'] ,dtype = 'str')

In [14]:
arr6.dtype

dtype('<U5')

In [15]:
# (Object) Elements of mixed datatypes in one array
# this datatype sacrifices performance. Therefore, we only used it when necessary.
arr7 = np.array([{'abc' : 123}, ['apple', 'b','s'], (1,3,5), {2.9,7.4, 6.2}], dtype = object)

In [16]:
arr7

array([{'abc': 123}, list(['apple', 'b', 's']), (1, 3, 5),
       {2.9, 6.2, 7.4}], dtype=object)

In [17]:
type(arr7[3])

set

In [18]:
type(arr7[0])

dict

- Numpy support these datatypes:
  - int32, int64, float32, float64, complex64, comlex128, str or U, object

In [19]:
# Downcasting
dcarr = arr1.astype('int32')

In [20]:
dcarr

array([2, 5, 8, 7], dtype=int32)

In [25]:
dcarr.dtype

dtype('int32')

In [26]:
floatintoint = arr2.astype('int32')    # casting (float into int)

In [27]:
floatintoint

array([5, 8, 2, 9], dtype=int32)

In [33]:
arr8 = np.array([4,7,9,1])

In [34]:
dcarr.nbytes

16

In [35]:
arr8.nbytes 

32

In [36]:
# nbytes increase when more elments are inserted in numpy array