# Broadcasting in Numpy
- Broadcasting is NumPy's ability to perform operations on arrays of different shapes by automatically "stretching" the smaller array to match the larger one -- without actually copying data.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a + 10) 

[11 12 13]


In [4]:
# Scaler 10 is broadcasted across all elements of an array

In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])   # shape (2, 3)

row    = np.array([10, 20, 30]) # shape (3,)

print(matrix + row)

[[11 22 33]
 [14 25 36]]


In [6]:
# row is broadcast across each row of matrix.

In [8]:
threerowsonecol = np.array([[2],
                      [6],
                      [5]])
onerowfourcol = np.array([1,4,8,7])
result = threerowsonecol + onerowfourcol

In [9]:
result

array([[ 3,  6, 10,  9],
       [ 7, 10, 14, 13],
       [ 6,  9, 13, 12]])

In [10]:
col = np.array([[1], [2], [3]])  
row = np.array([10, 20, 30])   

print(col + row)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [11]:
# This creates a full 3×3 matrix from two 1D-ish arrays 

### Broadcasting Rules
- NumPy compares shapes from the right dimension by dimension. Two dimensions are compatible if they are either equal or one of them is 1.