# Built in methods in Numpy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([2,5,9,12,45,89])

In [3]:
arr2 = np.array([23,56,89,12,34,12])

In [4]:
np.add(arr1, arr2)

array([ 25,  61,  98,  24,  79, 101])

In [5]:
np.append(3, arr1)

array([ 3,  2,  5,  9, 12, 45, 89])

In [6]:
np.amax(arr2)

np.int64(89)

In [7]:
np.amin(arr2)

np.int64(12)

In [8]:
np.argmax(arr1)     # return the index of max number

np.int64(5)

In [9]:
np.argmin(arr1)

np.int64(0)

In [10]:
np.array_equal(arr1, arr2)

False

In [11]:
np.asmatrix(arr1)

matrix([[ 2,  5,  9, 12, 45, 89]])

In [12]:
np.cumprod(arr2) #First number multiply with 1 then multipy each number with next number. Result of this multipy with next number and so on.

array([       23,      1288,    114632,   1375584,  46769856, 561238272])

In [13]:
np.cumulative_sum(arr1)

array([  2,   7,  16,  28,  73, 162])

In [14]:
np.mean(arr2)

np.float64(37.666666666666664)

In [15]:
np.multiply(arr1, arr2)

array([  46,  280,  801,  144, 1530, 1068])

In [17]:
# Simulating a dataset (5 samples (rows), 3 features (columns))
data = np.array([[10, 20, 30],
                [15, 25, 35],
                 [20,30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

mean = data.mean(axis = 0)
std = data.std(axis = 0)

normal_data = (data - mean)/std
print(normal_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
